import { readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import type { Plugin } from 'vite'

function parseWebDavFrontmatter(content: string) {
  if (!/^source:\s*webdav\s*$/m.test(content))
    return null

  const blockMatch = content.match(/^webdav:\s*\n((?:[ \t]+.+\n?)+)/m)
  if (!blockMatch)
    return null

  const block = blockMatch[1]
  const url = block.match(/^\s*url:\s*(.+)\s*$/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '')
  if (!url)
    return null

  const username = block.match(/^\s*username:\s*(.+)\s*$/m)?.[1]?.trim().replace(/^['"]|['"]$/g, '')

  return { url, username: username || undefined }
}

function scanAlbumWebDavConfig(root: string) {
  const galleryDirs = [
    resolve(root, 'content/gallery'),
    resolve(root, 'pages/gallery'),
  ]
  const configs: Record<string, { url: string, username?: string }> = {}

  for (const galleryDir of galleryDirs) {
    let entries: import('node:fs').Dirent[] = []
    try {
      entries = readdirSync(galleryDir, { withFileTypes: true })
    }
    catch {
      continue
    }

    for (const entry of entries) {
      if (!entry.isDirectory())
        continue

      const mdPath = join(galleryDir, entry.name, 'index.md')
      try {
        const content = readFileSync(mdPath, 'utf8')
        const parsed = parseWebDavFrontmatter(content)
        if (parsed)
          configs[entry.name] = parsed
      }
      catch {
        // ignore missing album index
      }
    }
  }

  return configs
}

function writeWebDavConfigFile(root: string) {
  const configs = scanAlbumWebDavConfig(root)
  const lines = Object.entries(configs)
    .map(([slug, config]) => `  '${slug}': ${JSON.stringify(config)},`)
    .join('\n')

  const file = `// auto-generated by album-webdav-config plugin
import type { AlbumWebDavFrontmatterConfig } from '../types/album'

export const albumWebDavPublicConfig: Record<string, AlbumWebDavFrontmatterConfig> = {
${lines}
}

export function getAlbumWebDavPublicConfig(slug: string) {
  return albumWebDavPublicConfig[slug]
}
`

  writeFileSync(resolve(root, 'server/albumWebdavPublicConfig.ts'), file, 'utf8')
}

export function albumWebdavConfigPlugin(): Plugin {
  const root = process.cwd()
  const generate = () => writeWebDavConfigFile(root)

  return {
    name: 'album-webdav-config',
    buildStart: generate,
    configureServer(server) {
      generate()
      server.watcher.on('change', (file) => {
        if ((file.includes('gallery') && file.endsWith('index.md')))
          generate()
      })
    },
  }
}
