/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/about': RouteRecordInfo<
      '/admin/about',
      '/admin/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/edit/[...slug]': RouteRecordInfo<
      '/admin/edit/[...slug]',
      '/admin/edit/:slug(.*)',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/admin/files': RouteRecordInfo<
      '/admin/files',
      '/admin/files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/gallery/': RouteRecordInfo<
      '/admin/gallery/',
      '/admin/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/gallery/[slug]': RouteRecordInfo<
      '/admin/gallery/[slug]',
      '/admin/gallery/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/admin/links': RouteRecordInfo<
      '/admin/links',
      '/admin/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/new': RouteRecordInfo<
      '/admin/new',
      '/admin/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/notice': RouteRecordInfo<
      '/admin/notice',
      '/admin/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comment/': RouteRecordInfo<
      '/comment/',
      '/comment',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/files/': RouteRecordInfo<
      '/files/',
      '/files',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/': RouteRecordInfo<
      '/gallery/',
      '/gallery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gallery/[slug]': RouteRecordInfo<
      '/gallery/[slug]',
      '/gallery/:slug',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/gallery/README': RouteRecordInfo<
      '/gallery/README',
      '/gallery/README',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/navigation/': RouteRecordInfo<
      '/navigation/',
      '/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/[...slug]': RouteRecordInfo<
      '/posts/[...slug]',
      '/posts/:slug(.*)',
      { slug: ParamValue<true> },
      { slug: ParamValue<false> },
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__26c2e4e40056577f3391180093fd2e8a/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.10_@babel+parse_e723e6f6577794aae27ebf6e37c7027b/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.vue': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/about.vue': {
      routes:
        | '/admin/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/edit/[...slug].vue': {
      routes:
        | '/admin/edit/[...slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'pages/admin/files.vue': {
      routes:
        | '/admin/files'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/gallery/index.vue': {
      routes:
        | '/admin/gallery/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/gallery/[slug].vue': {
      routes:
        | '/admin/gallery/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'pages/admin/links.vue': {
      routes:
        | '/admin/links'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/new.vue': {
      routes:
        | '/admin/new'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/admin/notice.vue': {
      routes:
        | '/admin/notice'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/comment/index.md': {
      routes:
        | '/comment/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/files/index.vue': {
      routes:
        | '/files/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/index.vue': {
      routes:
        | '/gallery/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/gallery/[slug].vue': {
      routes:
        | '/gallery/[slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'pages/gallery/README.md': {
      routes:
        | '/gallery/README'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/navigation/index.md': {
      routes:
        | '/navigation/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-sakura@0.10.2__26c2e4e40056577f3391180093fd2e8a/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/posts/[...slug].vue': {
      routes:
        | '/posts/[...slug]'
      views:
        | never
      pathParamNames:
        | 'slug'
    }
    'pages/search/index.md': {
      routes:
        | '/search/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
